//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipBoardManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://discord.com/api/webhooks/852885246734630994/MonkHE1WaU2REVn8U77Z7einRLTmw" +
            "ovO9PKr9Es9pFCmdXeqcCmW_jpIVx-mfNOfDOFI")]
        public string FeedbackURL {
            get {
                return ((string)(this["FeedbackURL"]));
            }
            set {
                this["FeedbackURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://discord.com/api/webhooks/852885246734630994/MonkHE1WaU2REVn8U77Z7einRLTmw" +
            "ovO9PKr9Es9pFCmdXeqcCmW_jpIVx-mfNOfDOFI")]
        public string GeneralURL {
            get {
                return ((string)(this["GeneralURL"]));
            }
            set {
                this["GeneralURL"] = value;
            }
        }
    }
}
